// Auto-generated by designlang — component anatomy v2.
// Scaffolds. Wire into your token system; not a runtime library.

import * as React from 'react';

export interface InputProps {
  variant?: 'default';
  size?: 'md';
  children?: React.ReactNode;
}

export function Input({ variant = 'default', size = 'md', ...rest }: InputProps) {
  return React.createElement('input', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface CardProps {
  variant?: 'default';
  size?: 'md';
  children?: React.ReactNode;
}

export function Card({ variant = 'default', size = 'md', ...rest }: CardProps) {
  return React.createElement('div', { 'data-variant': variant, 'data-size': size, ...rest });
}

export interface ButtonProps {
  variant?: 'primary';
  size?: 'lg';
  children?: React.ReactNode;
}

export function Button({ variant = 'primary', size = 'lg', ...rest }: ButtonProps) {
  return React.createElement('button', { 'data-variant': variant, 'data-size': size, ...rest });
}
