// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://coderthemes.com
// Generated: 2026-06-04T15:55:53.829Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#374760' | '#000000' | '#ffffff' | '#6c757d' | '#96a6b7' | '#2f75d0' | '#7c8bad' | '#ff0000' | '#444444' | '#dc3545' | '#343a40' | '#007bff' | '#ffc107' | '#28a745' | '#17a2b8' | '#495057' | '#edf0f3' | '#c1c1c1' | '#cccccc';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'hkgrotesk';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '600';

export type SpacingToken = '4px' | '48px' | '54px' | '70px' | '88px' | '95px' | '150px' | '190px' | '200px' | '210px' | '230px' | '308px';

export type RadiusToken = '3px' | '50px';

export type DurationToken = '150ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
